
rootdir  = '/Users/roee/Starr_Lab_Folder/Data_Analysis/Raw_Data/BR_reorganized';
resultsdir   = fullfile('..','results','mat_file_with_all_session_jsons');
evalc('mkdir(resultsdir)');
outdir   = fullfile('..','results','xls_files_of_session_db_by_patient');
evalc('mkdir(outdir)');

[settings, params] = get_settings_params();
load(fullfile(resultsdir,'all_session_celldb.mat'),'outdb','sessiondb','symptomcat');



%% some exapmples of sorting, data selections:
% inclusion criteria:
patients = unique(sessiondb.patientcode);
visits = unique(sessiondb.visitCategory);
visitsuse = visits([10    11     9     7     2     4     6     8     3     5]);
p = 1;
%% inclusion criteria
for p = 1:length(patients);
    rowsselect = ...
        sessiondb.usevisit == 1 & ...
        strcmp(sessiondb.patientcode,patients(p)) & ...
        ~strcmp(sessiondb.ConditionTask,'homeRecording') & ....
        ~strcmp(sessiondb.ConditionTask,'montage') & ...
        ~strcmp(sessiondb.xlsstatus,'sessionNotExistInXLS');
    colshow = {'patientcode',...
        'visitCategory',...
        'usevisit',...
        'sessionSerialNum',...
        'Medication',...
        'ConditionTask',...
        'StimOn',...
        'sr',...
        'RecordingType',...
        'stn_electrodes',...
        'm1_electrodes',...
        'symptoms',...
        'xlsstatus'};
    
    newdb = sessiondb(rowsselect,colshow);
    writetable(newdb,fullfile(outdir,[patients{p} '.csv']),'FileType','text');
end

%% write missing condition / task to file for all patients 
rowsselect = ...
    sessiondb.usevisit == 1 & ...
    ~strcmp(sessiondb.ConditionTask,'homeRecording') & ....
    ~strcmp(sessiondb.ConditionTask,'montage') & ...
    strcmp(sessiondb.ConditionTask,'') & ...
    ~strcmp(sessiondb.xlsstatus,'sessionNotExistInXLS');
colshow = {'patientcode',...
    'visitCategory',...
    'filename',...
    'usevisit',...
    'sessionSerialNum',...
    'Medication',...
    'ConditionTask',...
    'StimOn',...
    'sr',...
    'RecordingType',...
    'stn_electrodes',...
    'm1_electrodes',...
    'symptoms',...
    'xlsstatus'};

newdb = sessiondb(rowsselect,colshow);
writetable(newdb,fullfile(outdir,['missing_conditions_all_subs' '.csv']),'FileType','text');

%% write missing medication status rest files 
rowsselect = ...
    sessiondb.usevisit == 1 & ...
    strcmp(sessiondb.ConditionTask,'rest') & ....
    ~strcmp(sessiondb.Medication,'on') & ...
    ~strcmp(sessiondb.Medication,'off') & ...
    ~strcmp(sessiondb.xlsstatus,'sessionNotExistInXLS');
colshow = {'patientcode',...
    'visitCategory',...
    'filename',...
    'usevisit',...
    'sessionSerialNum',...
    'Medication',...
    'ConditionTask',...
    'StimOn',...
    'sr',...
    'RecordingType',...
    'stn_electrodes',...
    'm1_electrodes',...
    'symptoms',...
    'xlsstatus'};

newdb = sessiondb(rowsselect,colshow);
writetable(newdb,fullfile(outdir,['missing_medication_status_all_subs' '.csv']),'FileType','text');

%% write missing  stimulation status rest files 
rowsselect = ...
    sessiondb.usevisit == 1 & ...
    strcmp(sessiondb.ConditionTask,'rest') & ....
    ~strcmp(sessiondb.StimOn,'on') & ...
    ~strcmp(sessiondb.StimOn,'off') & ...
    ~strcmp(sessiondb.xlsstatus,'sessionNotExistInXLS');
colshow = {'patientcode',...
    'visitCategory',...
    'filename',...
    'usevisit',...
    'sessionSerialNum',...
    'Medication',...
    'ConditionTask',...
    'StimOn',...
    'sr',...
    'RecordingType',...
    'stn_electrodes',...
    'm1_electrodes',...
    'symptoms',...
    'xlsstatus'};

newdb = sessiondb(rowsselect,colshow);
writetable(newdb,fullfile(outdir,['missing_stim_status_all_subs' '.csv']),'FileType','text');

