function ...
    [ertf,...
    zertf,...
    mean_of_prestimulus_segment_of_ertf,...
    std_of_prestimulus_segment_of_ertf]=...
    make_zertf_and_zitc_for_many_ipad_eegfilt(...
    analytic_signals,...
    event_indices,...
    start_epoch_at_this_sample_point,...
    stop_epoch_at_this_sample_point,...
    start_baseline_at_this_sample_point,...
    stop_baseline_at_this_sample_point)
% function
%     [ertf,...
%     zertf,...
%     mean_of_prestimulus_segment_of_ertf,...
%     surrogate_ertf_fit,...
%     itc,...
%     zitc,...
%     surrogate_itc_fit]=...
%     make_zertf_and_zitc_for_many_frequencies_for_one_condition(...
%     analytic_signals,...
%     event_indices,...
%     start_epoch_at_this_sample_point,...
%     stop_epoch_at_this_sample_point,...
%     start_baseline_at_this_sample_point,...
%     stop_baseline_at_this_sample_point,...
%     skip)

number_of_frequencies=size(analytic_signals,1);                 %initilize variables
number_of_sample_points_in_signal=size(analytic_signals,2);


event_indices(find(event_indices<...                        %take out ones too close to the end or the begining
    abs(start_epoch_at_this_sample_point)))=[];
event_indices(find(event_indices>...
    number_of_sample_points_in_signal-...
    abs(stop_epoch_at_this_sample_point)))=[];
number_of_epochs=length(event_indices);
number_of_sample_points_in_epoch=...
    length(...
    start_epoch_at_this_sample_point:...
    stop_epoch_at_this_sample_point);

ertf=zeros(...
    number_of_frequencies,...
    number_of_sample_points_in_epoch,'single');
zertf=zeros(size(ertf),'single');


for e=1:number_of_epochs
%    disp(['epochs remaining = ' int2str(e)]);
    segment=analytic_signals(:,...    
        event_indices(e)+...
        (start_epoch_at_this_sample_point:...
        stop_epoch_at_this_sample_point));
    
    ertf=ertf+abs(segment); %for each trial, takes out ampltitude 
    
end
normalizer=1/number_of_epochs;
ertf=ertf*normalizer; %averages


mean_of_prestimulus_segment_of_ertf=...      %finds baseline values, (before stimulus), 
    mean(...
    ertf(:,abs(start_epoch_at_this_sample_point)+...
    (start_baseline_at_this_sample_point+1:...
    stop_baseline_at_this_sample_point)),2);

std_of_prestimulus_segment_of_ertf=...      %finds baseline values, (before stimulus), 
    std(...
    ertf(:,abs(start_epoch_at_this_sample_point)+...
    (start_baseline_at_this_sample_point+1:...
    stop_baseline_at_this_sample_point)),[],2);

ertf=ertf-repmat(...                            %subtracts the baseline
    mean_of_prestimulus_segment_of_ertf,1,size(ertf,2));

zertf = ertf./std_of_prestimulus_segment_of_ertf;

